- hosts: local
  remote_user: cloud
  sudo: true

  tasks:

    - name: add epel repository
      yum:
        name: epel-release
        state: present

    - name: haveged installed
      yum:
        name=haveged
        state=present
        update_cache=yes

    - name: haveged always running
      service:
        name=haveged
        state=started
        enabled=yes

    # - name: haveged unmasked
    #   shell: service nginx unmask

    - name: add zeroconf
      lineinfile:
        dest=/etc/sysconfig/network
        line="NOZEROCONF=yes"

    - name: sudo without tty
      lineinfile:
        dest=/etc/sudoers
        state=absent
        regexp="^Defaults\s*requiretty$"

    - name: packages installed
      yum:
        pkg={{ item }}
        state=present
      with_items:
        - parted
        - git

    - name: /etc/fstab contains /dev/vda1 rather than UUID
      replace:
        dest=/etc/fstab
        regexp='^UUID=.*?\s'
        replace='/dev/vda1 '

    - name: /boot/grub/menu.lst contains /dev/vda1 rather than UUID
      replace:
        dest=/boot/grub/menu.lst
        regexp='UUID=.*?\s'
        replace='/dev/vda1 '

    - name: packages installed
      pip:
        pkg={{ item }}
        state=absent
      with_items:
        - ansible
        - cryptography


    - name: packages installed
      yum:
        pkg={{ item }}
        state=absent
      with_items:
        - python-pip
        - python-crypto

    - name: add epel repository
      yum:
        name: epel-release
        state: absent

    - name: rm pop
      command: |
        sudo rm -rf /usr/lib64/python2.7/site-packages/pycrypto-2.6* &&\
        sudo dd if=/dev/zero of=/home/empty.dd bs=1048576" &&\
        sudo rm -rf /home/empty.dd
