- hosts: packer
  become: true

  tasks:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes


    - name: base toolkit
      apt: name={{ item }} state=present
      with_items:
        - haveged
        - curl
        - bzip2
        - unzip


   # - name: debian user removed
   #   user:
   #     name: {{ item }}
   #   with_items:
   #     - debian
   #     - ubuntu
   #     state: absent
   #     remove: yes
    - name: stopping system logging for cleaning
      service:
        name: rsyslog
        state: topped
        enabled: yes

    - name: rm logs
      file: path={{ item }} state=absent
      with_items: |
        - /home/cloud/.ssh/authorized_keys
        - /var/log/cloud-init
        - /home/cloud/known_hosts
        - /var/log/*-????????
        - /var/log/*.gz
        - /var/log/dmesg.old
        - /var/log/anaconda
        - /tmp/*
        - /var/tmp/*
        - ~root/.bash_history
        - ~root/.ssh/
        - ~root/anaconda-ks.cfg
        - ~cloud/.bash_history
        - ~cloud/.ssh/
        - ~cloud/anaconda-ks.cfg
      ignore_errors: true


   # - name: nettoyage
   #   command: |
   #     sudo rm -rf /usr/lib64/python2.7/site-packages/pycrypto-2.6* &&\
   #     sudo dd if=/dev/zero of=/home/empty.dd bs=1048576" &&\
   #     sudo rm -rf /home/empty.dd


    - name: remove user ubuntu
      user:
         name: ubuntu
         state: absent
         remove: yes
      become: true
      become_user: root