#cloud-config
users:
   - default
   -  name: cloud
      lock_passwd: true
      gecos: Cloud User
      groups: [wheel, adm, systemd-journal]
      sudo: ["ALL=(ALL) NOPASSWD:ALL"]
      shell: /bin/bash